
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gethn_development
test:
  <<: *default
  database: gethn_test

production:
  <<: *default
  database: gethn_production
  username: gethn
  password: <%= ENV['GETHN_DATABASE_PASSWORD'] %>
