# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c513175b535e30b2b037b81323b92a9af839bb0157ad4c3f2b88da31a716df98750c7afbbc6d2a7b60cc0208131ae0c84fb08aa6bfeeb988ece5f7555aec465e

test:
  secret_key_base: f10f3bd73149b2fcc2728be4a6114e8675f972929cb447fc0f8385727e501ea6c4d39a247605f70a6c195a37f013b2fc8d487bd2eaa32172a29c18c9b85ecfae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
